In [18]:
import pandas as pd
import seaborn as sns 
import numpy as np
import glob
import matplotlib.pyplot as plt
%matplotlib inline
%config Completer.use_jedi = False

In [19]:
#Import eQTL 95 and FPKM files for required cancer type

FPKM_file = '/Users/jake/OneDrive - University of Glasgow/Project/COAD/GeneExpression_MAF/COAD_FPKM_protein_all.csv'
FPKM = pd.read_csv(FPKM_file,sep='\t',header=[0,1],index_col=[0])


#Add path to eQTL files
path = r'/Users/jake/OneDrive - University of Glasgow/Project/COAD/eQTL/eQTL_95'

all_files = glob.glob(path + "/*.csv")

#For loop to read in eQTL files        
for filename in all_files:
    
    if 'cis_symbol_95' in filename:
        cis_symbol_95 = pd.read_csv(filename,sep='\t')
    elif 'cis_entrez_95' in filename:
        cis_entrez_95 = pd.read_csv(filename, sep='\t')
    elif 'trans_symbol_95' in filename:
        trans_symbol_95 = pd.read_csv(filename,sep='\t')
    elif 'trans_entrez_95' in filename:
        trans_entrez_95 = pd.read_csv(filename,sep='\t')

In [20]:
cis_symbol_95.head()

,Gene_symbol,Entrez_ID,Value_count,ensembl_gene_id,entrezgene_id,chromosome_name
1,LOC399744,399744,1638,NaN,NaN,NaN
2,FABP2,2169,1076,ENSG00000145384,2169.0,4.0
3,SNHG5,387066,1039,ENSG00000203875,NaN,6.0
4,ZNF117,51351,998,ENSG00000152926,51351.0,7.0
5,ZNF117,51351,998,ENSG00000152926,109504726.0,7.0

In [21]:
trans_symbol_95.head()

,Gene_symbol,Entrez_ID,Value_count,ensembl_gene_id,entrezgene_id,chromosome_name
1,CCDC74B,91409,384,ENSG00000152076,91409.0,2.0
2,LOC285359,285359,287,NaN,NaN,NaN
3,ZNF322B,387328,273,NaN,NaN,NaN
4,INTS4L1,285905,147,NaN,NaN,NaN
5,LOC647288,647288,116,NaN,NaN,NaN

In [22]:
#Concat cis_entrez and cis_symbol and drop any rows with NA for Ensembl Id
#Also drop duplicates in Ensembl ID col

cis_eQTL_95 = pd.concat([cis_entrez_95,cis_symbol_95]).dropna(axis=0,subset=['ensembl_gene_id']).drop_duplicates(subset = 'ensembl_gene_id')

In [23]:
#Drop hgnc_symbol and entregene_id cols 
#=> keeping hg38 determined ensembl_id alongside original Gene_symol (hg19) 

cis_eQTL_95.drop(['hgnc_symbol','entrezgene_id'],axis=1,inplace=True)
cis_eQTL_95.reset_index(drop=True)

    Gene_symbol  Entrez_ID  Value_count  ensembl_gene_id  chromosome_name
0         FABP2       2169         1076  ENSG00000145384              4.0
1        ZNF117      51351          998  ENSG00000152926              7.0
2          XKR9     389668          980  ENSG00000221947              8.0
3        NUDT13      25961          910  ENSG00000166321             10.0
4       C2orf74     339804          891  ENSG00000237651              2.0
..          ...        ...          ...              ...              ...
239     FAM182B     728882          460  ENSG00000175170             20.0
240     PI4KAP2     375133          418  ENSG00000183506             22.0
241     DHX40P1     653645          208  ENSG00000266992             17.0
242     DDX11L2      84771          189  ENSG00000236397              2.0
243    RPL23AP7     118433          171  ENSG00000240356              2.0

[244 rows x 5 columns]

In [24]:
#Check for duplicates in 'Gene_symbol'

cis_eQTL_95[cis_eQTL_95.duplicated(['Gene_symbol'])]

    Gene_symbol  Entrez_ID  Value_count  ensembl_gene_id  chromosome_name
185     DHX40P1     653645          208  ENSG00000266992             17.0
213     DDX11L2      84771          189  ENSG00000236397              2.0

In [25]:
#Check the Ensembl ID of any duplicates

cis_eQTL_95[cis_eQTL_95['Gene_symbol'] == 'DHX40P1']

    Gene_symbol  Entrez_ID  Value_count  ensembl_gene_id  chromosome_name
183     DHX40P1     653645          208  ENSG00000267104             17.0
185     DHX40P1     653645          208  ENSG00000266992             17.0

In [26]:
#Check FPKM for duplicate

FPKM.xs('ENSG00000266992',level='Gene_ensembl_id',axis=1)

KeyError: 'ENSG00000266992'

In [ ]:
#Drop any duplicate not mathcing FPKM

#cis_eQTL_95 = cis_eQTL_95[~cis_eQTL_95['ensembl_gene_id'].isin(['ENSG00000229415'])]
cis_eQTL_95 = cis_eQTL_95[~cis_eQTL_95['Gene_symbol'].isin(['DDX11L2','DHX40P1'])]

In [ ]:
#Reset index

cis_eQTL_95.reset_index(drop=True)

#Display number of cis eQTL
cis_eQTL_95['Gene_symbol'].nunique()

In [ ]:
#Repeat process for trans eQTL

In [ ]:
#Concat trans_entrez and trans_symbol and drop any rows with NA for Ensembl Id
#Also drop duplicates in Ensembl ID col

trans_eQTL_95 = pd.concat([trans_entrez_95,trans_symbol_95]).dropna(axis=0,subset=['ensembl_gene_id']).drop_duplicates(subset = 'ensembl_gene_id')

In [ ]:
#Drop hgnc_symbol and entregene_id cols 
#=> keeping hg38 determined ensembl_id alongside original Gene_symol (hg19) 

trans_eQTL_95.drop(['hgnc_symbol','entrezgene_id'],axis=1,inplace=True)
trans_eQTL_95.reset_index(drop=True)

In [ ]:
#Check for duplicates in 'Gene_symbol'

trans_eQTL_95[trans_eQTL_95.duplicated(['Gene_symbol'])]

In [ ]:

#trans_eQTL_95[cis_eQTL_95['Gene_symbol'] == '']

In [ ]:
#Drop any duplicate not mathcing FPKM

#trans_eQTL_95 = trans_eQTL_95[~trans_eQTL_95['ensembl_gene_id'].isin(['ENSG00000229415'])]
#trans_eQTL_95 = trans_eQTL_95[~trans_eQTL_95['Gene_symbol'].isin(['PINX1'])]

In [ ]:
#Reset index

trans_eQTL_95.reset_index(drop=True)

#Display number of trans eQTL
trans_eQTL_95['Gene_symbol'].nunique()

In [ ]:
#Write cis and trans dataframes to csv

cis_eQTL_95.to_csv(path.split('/')[5]+'_cis_eQTL_95_ensembl.csv',sep='\t')
trans_eQTL_95.to_csv(path.split('/')[5]+'_trans_eQTL_95_ensembl.csv',sep='\t')