In [1]:
import pandas as pd
import seaborn as sns 
import numpy as np
import glob
import matplotlib.pyplot as plt
%matplotlib inline
%config Completer.use_jedi = False

In [2]:
#Import FPKM, MAF_protein and eQTL files for required cancer type

#Add path to eQTL files
path = r'/Users/jake/OneDrive - University of Glasgow/Project/COAD/eQTL'

all_files = glob.glob(path + "/*.txt")

#For loop to read in eQTL files        
for filename in all_files:
    
    if 'cis' in filename:
        cis_eQTL = pd.read_csv(filename,sep='\t')
    elif 'trans' in filename:
        trans_eQTL = pd.read_csv(filename, sep='\t')

In [3]:
cis_eQTL.head()

,SNP,gene,beta,t-stat,p-value,FDR
0,rs6531717:39454321:G:A,RPL9|6133,-1.138911,-33.024236,3.429985e-95,1.639675e-87
1,rs2687969:39452499:T:C,RPL9|6133,-1.135399,-32.763508,1.818892e-94,4.347531e-87
2,rs2249563:39455378:A:G,RPL9|6133,-1.134352,-31.943949,3.633020e-92,2.481049e-85
3,rs2687955:39457153:C:T,RPL9|6133,-1.134352,-31.943949,3.633020e-92,2.481049e-85
4,rs2687956:39457430:T:C,RPL9|6133,-1.134352,-31.943949,3.633020e-92,2.481049e-85

In [12]:
#Create new SNP columsn by splitting the SNP column and also remove numbers from gene names

cis_eQTL['Gene_symbol'] = cis_eQTL['gene'].apply(lambda gene: gene.split('|')[0])
cis_eQTL['Entrez_ID'] = cis_eQTL['gene'].apply(lambda gene: gene.split('|')[1])
cis_eQTL['cis_SNP_ID'] = cis_eQTL['SNP'].apply(lambda x: x.split(':')[0])
cis_eQTL['SNP_Position_Chr (hg19)'] = cis_eQTL['SNP'].apply(lambda x: x.split(':')[1])
cis_eQTL['SNP_Allele'] = cis_eQTL['SNP'].apply(lambda x: x.split(':')[2] + '/' + x.split(':')[3])

#Drop old SNP and gene col
cis_eQTL.drop(['SNP','gene'],axis =1 ,inplace=True)

In [13]:
cis_eQTL

,beta,t-stat,p-value,FDR,Gene_symbol,Entrez_ID,cis_SNP_ID,SNP_Position_Chr (hg19),SNP_Allele
0,-1.138911,-33.024236,3.429985e-95,1.639675e-87,RPL9,6133,rs6531717,39454321,G/A
1,-1.135399,-32.763508,1.818892e-94,4.347531e-87,RPL9,6133,rs2687969,39452499,T/C
2,-1.134352,-31.943949,3.633020e-92,2.481049e-85,RPL9,6133,rs2249563,39455378,A/G
3,-1.134352,-31.943949,3.633020e-92,2.481049e-85,RPL9,6133,rs2687955,39457153,C/T
4,-1.134352,-31.943949,3.633020e-92,2.481049e-85,RPL9,6133,rs2687956,39457430,T/C
...,...,...,...,...,...,...,...,...,...
164351,0.259668,3.812216,1.718889e-04,4.999637e-02,C6orf164,63914,rs6454590,87888947,A/G
164352,0.278608,3.812207,1.718950e-04,4.999721e-02,PM20D1,148811,rs60092747,205829587,A/G
164353,0.278608,3.812207,1.718950e-04,4.999721e-02,PM20D1,148811,rs57897938,205831735,T/G
164354,-0.311958,-3.812206,1.718960e-04,4.999721e-02,PYGL,5836,rs7160810,51716467,G/A
164355,-0.311958,-3.812206,1.718960e-04,4.999721e-02,PYGL,5836,rs7350715,51717060,C/A

In [14]:
#Now repeat process for the trans_eQTLS

trans_eQTL['Gene_symbol'] = trans_eQTL['gene'].apply(lambda gene: gene.split('|')[0])
trans_eQTL['Entrez_ID'] = trans_eQTL['gene'].apply(lambda gene: gene.split('|')[1])
trans_eQTL['trans_SNP_ID'] = trans_eQTL['SNP'].apply(lambda x: x.split(':')[0])
trans_eQTL['SNP_Position_Chr (hg19)'] = trans_eQTL['SNP'].apply(lambda x: x.split(':')[1])
trans_eQTL['SNP_Allele'] = trans_eQTL['SNP'].apply(lambda x: x.split(':')[2] + '/' + x.split(':')[3])

#Drop old SNP and gene col
trans_eQTL.drop(['SNP','gene'],axis =1 ,inplace=True)

In [15]:
trans_eQTL

,beta,t-stat,p-value,FDR,Gene_symbol,Entrez_ID,trans_SNP_ID,SNP_Position_Chr (hg19),SNP_Allele
0,0.919773,15.811843,5.858615e-40,4.655876e-29,HSP90AB2P,391634,rs13296,44218120,A/G
1,0.994873,15.474549,9.019558e-39,3.583948e-28,LOC388955,388955,rs28580074,176721198,T/C
2,0.984245,15.239219,6.069065e-38,1.607707e-27,LOC388955,388955,rs28684504,176727438,T/C
3,0.865920,15.096688,1.924334e-37,3.659264e-27,POM121L10P,646074,rs140507,23646512,C/T
4,0.865200,15.074532,2.302276e-37,3.659264e-27,POM121L10P,646074,rs131684,23646257,A/T
...,...,...,...,...,...,...,...,...,...
3080,0.375089,6.223921,1.922869e-09,4.959803e-02,MFAP3,4238,rs2971899,155689683,C/T
3081,0.494632,6.223513,1.927222e-09,4.969418e-02,SPG20,23111,rs78914116,106947414,C/T
3082,0.575847,6.222944,1.933321e-09,4.983526e-02,XPO7,23039,rs17611350,15302403,A/G
3083,-0.761130,-6.222831,1.934535e-09,4.985039e-02,INTS10,55174,rs7814718,29939046,C/T
3084,0.529846,6.222466,1.938455e-09,4.993522e-02,CCDC74B,91409,rs12988424,132250093,T/G

In [8]:
#Write the cis and trans tables to csv

cis_eQTL.to_csv(path.split('/')[5]+'_cis_eQTL.csv')
trans_eQTL.to_csv(path.split('/')[5]+'_trans_eQTL.csv')

In [21]:
trans_eQTL['Gene_symbol'].unique()[:10]

array(['HSP90AB2P', 'LOC388955', 'POM121L10P', 'LOC285359', 'LOC644172',
       'ZNF322B', 'INTS4L1', 'LOC647288', 'TUBB4Q', 'LRRC37A4'],
      dtype=object)

In [22]:
cis_eQTL['Gene_symbol'].unique()[:10]

array(['RPL9', 'ERAP2', 'RPS28', 'LQK1', 'SNHG5', 'XRRA1', 'TYW1B',
       'GBP3', 'WBSCR27', 'POMZP3'], dtype=object)