In [1]:
import pandas as pd
import seaborn as sns 
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

In [2]:
#Filenames

#MAF protein coding files
MAF_VEP_protein_tumour_file = '/Users/jake/OneDrive - University of Glasgow/Project/COAD/FPKM_MAF_notebook/COAD_protein_coding_tumour.csv'
MAF_VEP_protein_normal_file = '/Users/jake/OneDrive - University of Glasgow/Project/COAD/FPKM_MAF_notebook/COAD_protein_coding_normal.csv'

#Gene expression FPKM files
FPKM_tumour_file = '/Users/jake/OneDrive - University of Glasgow/Project/COAD/FPKM_MAF_notebook/COAD_FPKM_tumour.csv'
FPKM_normal_file = '/Users/jake/OneDrive - University of Glasgow/Project/COAD/FPKM_MAF_notebook/COAD_FPKM_normal.csv'

#eQTL files
cis_eQTL_file = '/Users/jake/OneDrive - University of Glasgow/Project/COAD/eQTL/COAD_tumor.cis_eQTL.txt'
trans_eQTL_file = '/Users/jake/OneDrive - University of Glasgow/Project/COAD/eQTL/COAD_tumor.trans_eQTL.txt'

In [3]:
#Load cis_eQTL and trans_eQTL files

cis_eQTL = pd.read_csv(cis_eQTL_file,sep='\t')
trans_eQTL = pd.read_csv(trans_eQTL_file,sep='\t')

In [4]:

cis_eQTL.head()

,SNP,gene,beta,t-stat,p-value,FDR
0,rs6531717:39454321:G:A,RPL9|6133,-1.138911,-33.024236,3.429985e-95,1.639675e-87
1,rs2687969:39452499:T:C,RPL9|6133,-1.135399,-32.763508,1.818892e-94,4.347531e-87
2,rs2249563:39455378:A:G,RPL9|6133,-1.134352,-31.943949,3.633020e-92,2.481049e-85
3,rs2687955:39457153:C:T,RPL9|6133,-1.134352,-31.943949,3.633020e-92,2.481049e-85
4,rs2687956:39457430:T:C,RPL9|6133,-1.134352,-31.943949,3.633020e-92,2.481049e-85

In [5]:
#Create new SNP columsn by splitting the SNP column and also remove numbers from gene names

cis_eQTL['Gene_symbol'] = cis_eQTL['gene'].apply(lambda gene: gene.split('|')[0])

cis_eQTL['cis_SNP_ID'] = cis_eQTL['SNP'].apply(lambda x: x.split(':')[0])
cis_eQTL['SNP_Position_Chr (hg19)'] = cis_eQTL['SNP'].apply(lambda x: x.split(':')[1])
cis_eQTL['SNP_Allele'] = cis_eQTL['SNP'].apply(lambda x: x.split(':')[2] + '/' + x.split(':')[3])

#Drop old SNP and gene col
cis_eQTL.drop(['SNP','gene'],axis =1 ,inplace=True)

In [6]:
cis_eQTL.head()

,beta,t-stat,p-value,FDR,Gene_symbol,cis_SNP_ID,SNP_Position_Chr (hg19),SNP_Allele
0,-1.138911,-33.024236,3.429985e-95,1.639675e-87,RPL9,rs6531717,39454321,G/A
1,-1.135399,-32.763508,1.818892e-94,4.347531e-87,RPL9,rs2687969,39452499,T/C
2,-1.134352,-31.943949,3.633020e-92,2.481049e-85,RPL9,rs2249563,39455378,A/G
3,-1.134352,-31.943949,3.633020e-92,2.481049e-85,RPL9,rs2687955,39457153,C/T
4,-1.134352,-31.943949,3.633020e-92,2.481049e-85,RPL9,rs2687956,39457430,T/C

In [7]:
#Now repeat process for the trans_eQTLS

trans_eQTL['Gene_symbol'] = trans_eQTL['gene'].apply(lambda gene: gene.split('|')[0])

trans_eQTL['trans_SNP_ID'] = trans_eQTL['SNP'].apply(lambda x: x.split(':')[0])
trans_eQTL['SNP_Position_Chr (hg19)'] = trans_eQTL['SNP'].apply(lambda x: x.split(':')[1])
trans_eQTL['SNP_Allele'] = trans_eQTL['SNP'].apply(lambda x: x.split(':')[2] + '/' + x.split(':')[3])

#Drop old SNP and gene col
trans_eQTL.drop(['SNP','gene'],axis =1 ,inplace=True)

In [8]:
trans_eQTL.head()

,beta,t-stat,p-value,FDR,Gene_symbol,trans_SNP_ID,SNP_Position_Chr (hg19),SNP_Allele
0,0.919773,15.811843,5.858615e-40,4.655876e-29,HSP90AB2P,rs13296,44218120,A/G
1,0.994873,15.474549,9.019558e-39,3.583948e-28,LOC388955,rs28580074,176721198,T/C
2,0.984245,15.239219,6.069065e-38,1.607707e-27,LOC388955,rs28684504,176727438,T/C
3,0.865920,15.096688,1.924334e-37,3.659264e-27,POM121L10P,rs140507,23646512,C/T
4,0.865200,15.074532,2.302276e-37,3.659264e-27,POM121L10P,rs131684,23646257,A/T

In [9]:
trans_eQTL['Gene_symbol'].value_counts()

CCDC74B      384
LOC285359    287
ZNF322B      273
INTS4L1      147
LOC647288    116
            ...
CRNKL1         1
PTPN9          1
EIF3J          1
DLGAP2         1
WASH5P         1
Name: Gene_symbol, Length: 373, dtype: int64

In [10]:
cis_eQTL['Gene_symbol'].value_counts()

LOC399744    1638
FABP2        1076
SNHG5        1039
ZNF117        998
XKR9          980
             ...
DDX39           1
NELL2           1
CDC42EP3        1
BCHE            1
ADH5            1
Name: Gene_symbol, Length: 5048, dtype: int64