In [1]:
import pandas as pd
import seaborn as sns 
import numpy as np
import glob
import matplotlib.pyplot as plt
%matplotlib inline
%config Completer.use_jedi = False

In [2]:
#Import eQTL files for required cancer type

#Add path to eQTL files
path = r'/Users/jake/OneDrive - University of Glasgow/Project/BRCA/eQTL'

all_files = glob.glob(path + "/*.txt")

#For loop to read in eQTL files        
for filename in all_files:
    
    if 'cis' in filename:
        cis_eQTL = pd.read_csv(filename,sep='\t')
    elif 'trans' in filename:
        trans_eQTL = pd.read_csv(filename, sep='\t')

In [3]:
cis_eQTL.head()

,SNP,gene,beta,t-stat,p-value,FDR
0,rs1458255:39446549:G:A,RPL9|6133,-1.160767,-54.786336,2.225074e-308,4.506577e-302
1,rs2608824:39447779:A:G,RPL9|6133,-1.163077,-54.995791,2.225074e-308,4.506577e-302
2,rs2687967:39449824:G:A,RPL9|6133,-1.162670,-55.904223,2.225074e-308,4.506577e-302
3,rs2687969:39452499:T:C,RPL9|6133,-1.163601,-56.783577,2.225074e-308,4.506577e-302
4,rs2608828:39453730:C:G:+,RPL9|6133,1.167124,60.627123,2.225074e-308,4.506577e-302

In [4]:
#Create new SNP columsn by splitting the SNP column and also remove numbers from gene names

cis_eQTL['Gene_symbol'] = cis_eQTL['gene'].apply(lambda gene: gene.split('|')[0])
cis_eQTL['Entrez_ID'] = cis_eQTL['gene'].apply(lambda gene: gene.split('|')[1])
cis_eQTL['cis_SNP_ID'] = cis_eQTL['SNP'].apply(lambda x: x.split(':')[0])
cis_eQTL['SNP_Position_Chr (hg19)'] = cis_eQTL['SNP'].apply(lambda x: x.split(':')[1])
cis_eQTL['SNP_Allele'] = cis_eQTL['SNP'].apply(lambda x: x.split(':')[2] + '/' + x.split(':')[3])

#Drop old SNP and gene col
cis_eQTL.drop(['SNP','gene'],axis =1 ,inplace=True)

In [5]:
cis_eQTL

,beta,t-stat,p-value,FDR,Gene_symbol,Entrez_ID,cis_SNP_ID,SNP_Position_Chr (hg19),SNP_Allele
0,-1.160767,-54.786336,2.225074e-308,4.506577e-302,RPL9,6133,rs1458255,39446549,G/A
1,-1.163077,-54.995791,2.225074e-308,4.506577e-302,RPL9,6133,rs2608824,39447779,A/G
2,-1.162670,-55.904223,2.225074e-308,4.506577e-302,RPL9,6133,rs2687967,39449824,G/A
3,-1.163601,-56.783577,2.225074e-308,4.506577e-302,RPL9,6133,rs2687969,39452499,T/C
4,1.167124,60.627123,2.225074e-308,4.506577e-302,RPL9,6133,rs2608828,39453730,C/G
...,...,...,...,...,...,...,...,...,...
438471,-0.205766,-3.371959,7.731290e-04,4.999660e-02,PROCR,10544,rs77595325,33402877,C/G
438472,0.090022,3.371956,7.731366e-04,4.999698e-02,POLR1A,25885,rs6758173,86462747,G/A
438473,0.130905,3.371949,7.731559e-04,4.999811e-02,B3GNT1,11041,rs72145138,65812497,GAGA/G
438474,-0.113940,-3.371947,7.731622e-04,4.999841e-02,REEP1,65055,rs147974092,86772110,A/G
438475,-0.110424,-3.371946,7.731651e-04,4.999848e-02,RASA4,10156,rs2860421,101498249,A/G

In [6]:
#Now repeat process for the trans_eQTLS

trans_eQTL['Gene_symbol'] = trans_eQTL['gene'].apply(lambda gene: gene.split('|')[0])
trans_eQTL['Entrez_ID'] = trans_eQTL['gene'].apply(lambda gene: gene.split('|')[1])
trans_eQTL['trans_SNP_ID'] = trans_eQTL['SNP'].apply(lambda x: x.split(':')[0])
trans_eQTL['SNP_Position_Chr (hg19)'] = trans_eQTL['SNP'].apply(lambda x: x.split(':')[1])
trans_eQTL['SNP_Allele'] = trans_eQTL['SNP'].apply(lambda x: x.split(':')[2] + '/' + x.split(':')[3])

#Drop old SNP and gene col
trans_eQTL.drop(['SNP','gene'],axis =1 ,inplace=True)

In [7]:
trans_eQTL

,beta,t-stat,p-value,FDR,Gene_symbol,Entrez_ID,trans_SNP_ID,SNP_Position_Chr (hg19),SNP_Allele
0,0.902210,29.844600,8.657869e-143,4.281499e-132,HSP90AB2P,391634,rs13296,44218120,A/G
1,-0.784819,-23.292321,2.368871e-97,5.857283e-87,HSP90AB2P,391634,rs504697,44220076,C/T
2,0.799159,22.814636,3.740225e-94,6.165401e-84,HSP90AB2P,391634,rs324130,44212688,T/C
3,0.936904,21.807257,1.743719e-87,2.155764e-77,LOC644172,644172,rs9896243,44826056,C/G
4,0.777056,21.636314,2.301390e-86,2.276172e-76,HSP90AB2P,391634,rs35131506,44222161,C/CTG
...,...,...,...,...,...,...,...,...,...
73119,-0.344296,-5.419405,7.390887e-08,4.998563e-02,ENTPD4,9583,rs169062,24675003,C/T
73120,0.121911,5.419374,7.392124e-08,4.999326e-02,APOA1BP,128240,rs6894865,6596721,C/T
73121,-0.219647,-5.419372,7.392217e-08,4.999326e-02,MRP63,78988,rs57639568,141785162,G/C
73122,-0.328777,-5.419363,7.392589e-08,4.999509e-02,C17orf81,23587,rs1006561,16412342,A/T
73123,0.330042,5.419348,7.393178e-08,4.999839e-02,FAM160B2,64760,rs17091870,19831630,C/G

In [8]:
#Write the cis and trans tables to csv

cis_eQTL.to_csv(path.split('/')[5]+'_cis_eQTL.csv')
trans_eQTL.to_csv(path.split('/')[5]+'_trans_eQTL.csv')